### ISSUE TITLE
Osu!test, test client from 2014 partially patched and fixed by me

### ISSUE THREAD

**Issue by Zordon1337** [osuTitanic/clients#4]
# Hello!
i want to share an client with you guys
it had an issue where it was bootlooping to updater and restarting, you can read details here: [https://osekai.net/snapshots/?version=88](https://osekai.net/snapshots/?version=88)

i fixed it(it normaly runs now) and patched it to ONLY connect to bancho(c.lekuru.xyz), rest of urls point to *.ppy.sh
![image](https://github.com/osuTitanic/clients/assets/65111609/2bca0841-d11c-4fe1-a122-f3093d31b702)

ps: it has date from 2015 in copyright but the client version name is: b20140909.11cuttingedge
so it's from 2014

i added small credit for me, if you want i can remove it
![image](https://github.com/osuTitanic/clients/assets/65111609/bda0240e-e718-4202-9522-b66390ecd026)

ps2(not the console): you need supporter to play so can't test if the rest of client works, also the version is too newer for backend so i can't login

ps3: i got the client from osekai also

client link(needed to upload it on mediafire because i forgor password to my ftp): https://www.mediafire.com/file/qb1llh1kwvnz08m/b20140909.11cuttingedge_patched.7z/file

**Comment by Zordon1337** [comment]
nvrmind i just saw that you only support client >= 2013
well, im gonna still leave it here maybe you will use it

**Comment by Lekuruu** [comment]
We are planning to support versions past 2013 clients soon. Pretty much everything has already been implemented for it. Thanks for your work and interest!

**Comment by Zordon1337** [comment]
> We are planning to support versions past 2013 clients soon. Pretty much everything has already been implemented for it. Thanks for your work and interest!

thats nice, does that small credits makes is an problem for you? or not

**Comment by Lekuruu** [comment]
It's totally fine, don't worry

**Comment by Lekuruu** [comment]
I can share some screenshots in a moment of it working ingame

**Comment by Lekuruu** [comment]
Seems like you forgot to patch some urls. Would you be able to do that?

**Comment by Zordon1337** [comment]
> Seems like you forgot to patch some urls. Would you be able to do that?

i mentioned it above that i only patched the server ip and yes i will patch rest

**Comment by Lekuruu** [comment]
Oh sorry I forgot to read that

**Comment by Zordon1337** [comment]
> Oh sorry I did not read that

i will patch most of them, because there is sometimes class that you can't compile due to being broken by obfuscation

**Comment by Lekuruu** [comment]
You should always be able to edit the assembly as a backup, so that you don't have to recompile it. I am also assuming you read this small guide: https://github.com/osuTitanic/clients/blob/main/PATCHING.md

**Comment by Zordon1337** [comment]
> You should always be able to edit the assembly as a backup, so that you don't have to recompile it. I am also assuming you read this small guide: https://github.com/osuTitanic/clients/blob/main/PATCHING.md

i mean, if you edit something in DnSpy it attempts to compile if there are errors you can't save
for example there is much errors so i can't edit that url


ps: we have the same methods of patching clients lol, because i were using the same method(thats probably the only one that is possible lol)

**Comment by Zordon1337** [comment]
![image](https://github.com/osuTitanic/clients/assets/65111609/ea5811a8-b41d-4b63-87f3-2824c16d602e)

**Comment by Zordon1337** [comment]
example of why i can't patch some urls

**Comment by Zordon1337** [comment]
but i found workaround for some of them

**Comment by Lekuruu** [comment]
What you showed here is not the assembly editor. This is something i forgot to include in the guide, and is a little bit more advanced. Here is an example:

![img](https://github.com/osuTitanic/clients/assets/84310095/e7a074d6-69a9-4eee-9cc9-fd321b309c1c)
![img2](https://github.com/osuTitanic/clients/assets/84310095/a0f5defb-84d2-4202-a9f4-647f1242cf05)

From here you can edit anything you want in raw dotnet assembly, which should work pretty much all of the time without issues.

**Comment by Zordon1337** [comment]
ok, thanks im gonna try it

**Comment by Zordon1337** [comment]
ok, done
![image](https://github.com/osuTitanic/clients/assets/65111609/a1c4eb91-a07e-442a-a4ea-0fb6769d9e96)
i replaced every url(one result is unrelated to url and other one is updated but dnspy doesn't see it)

**Comment by Zordon1337** [comment]
wait im gonna upload it

**Comment by Zordon1337** [comment]
https://cdn.zndev.xyz/b20140909.11cuttingedge_patched.zip 
here

**Comment by Lekuruu** [comment]
![screenshot001](https://github.com/osuTitanic/clients/assets/84310095/6e042368-2783-4fb7-8969-85f5d422035a)

works

**Comment by Lekuruu** [comment]
I will close this issue for now. We are not sure when we will release support for the next generation of osu! clients, but we sure are getting a lot of requests for them.
