### ISSUE TITLE
osu! build b20120916

### ISSUE THREAD

**Issue by Zordon1337** [osuTitanic/clients#5]
# Hello again
i came back with new build, this one is actually fully connecting
version: b20120916
most of osu.ppy.sh links were replaced by osu.lekuru.xyz
unfortunately the osu!direct doesn't work, it's reading maps but doesn't download them and returning error
![image](https://github.com/osuTitanic/clients/assets/65111609/3c17e1d9-7fd5-43bf-8297-c94212494127)
IRC Works,
Leaderboard works,
unfortunately the score submitting doesn't work and you get this error
![image](https://github.com/osuTitanic/clients/assets/65111609/8e560ac0-aade-4518-a6b5-35a56206e007)

![image](https://github.com/osuTitanic/clients/assets/65111609/233d780d-3001-4fd7-b668-1d1afdaa42ce)

Client here
[b20120916_patched.zip](https://github.com/osuTitanic/clients/files/13845202/b20120916_patched.zip)

**Comment by Lekuruu** [comment]
I am pretty confused on why this works, because we have verification checks for all clients that connect to bancho, to prevent people from creating simple cheats. But anyways... thank you for your contribution!

**Comment by Lekuruu** [comment]
You forgot to patch pretty much every ppy.sh domain. That would be the main reason why you are getting these errors in the first place.

**Comment by Zordon1337** [comment]
> You forgot to patch pretty much every ppy.sh domain. That would be the main reason why you are getting these errors in the first place.
im gonna do it tommorow

**Comment by Lekuruu** [comment]
man i am really good at reading

**Comment by Zordon1337** [comment]
hmmm, now after replacing every it got even worse 
![image](https://github.com/osuTitanic/clients/assets/65111609/09b08c35-ceec-4cae-9caf-19974e65c0f6)

**Comment by Zordon1337** [comment]
i replaced everything(one result is in something that contains cho.ppy.sh
![image](https://github.com/osuTitanic/clients/assets/65111609/0269f344-2ec4-45d9-aad0-f04a0ec01bc5)


build: http://cdn.zndev.xyz/b20120916_patched.7z

**Comment by Lekuruu** [comment]
I previously mentioned, we have verification methods that were previously not working, but are now. I will verify the client in a moment.

**Comment by Lekuruu** [comment]
The client seems to be working very well. I will included as soon as I can.

**Comment by Zordon1337** [comment]
> The client seems to be working very well. I will included as soon as I can.

so as i understand, the client works properly but before i login the server is checking im admin or is my version on list of supported and only admins can connect from every client that is not on list?

**Comment by Zordon1337** [comment]
ps: i think you replaced db2k client with mine, im not sure if you did that on accident or not

**Comment by Lekuruu** [comment]
The db2k client was not on osekai, so thats why I removed it.

**Comment by Lekuruu** [comment]
Done.

**Comment by Zordon1337** [comment]
![image](https://github.com/osuTitanic/clients/assets/65111609/fb0befd8-db54-49d2-930e-5800e72c36cb)

**Comment by Lekuruu** [comment]
Please refresh the browsers cache and try again. It should work after that.
