### ISSUE TITLE
osu b420 connects but server returns id -1

### ISSUE THREAD

**Issue by Zordon1337** [osuTitanic/clients#6]
# Hi
im trying to patch b420 but im stuck with the problem that on LoginReply the server returns -1 which client reads as Wrong Password/Username but both of them are correct

can you explain why server returns id -1?

**Comment by Zordon1337** [comment]
nvrmind, i know the reason
![image](https://github.com/osuTitanic/clients/assets/65111609/f1ada211-e7d1-4fba-91dd-752a8d9de4f0)

**Comment by Lekuruu** [comment]
Yeah, we need to verify it. If you can send it over, then i'll do that for you.

**Comment by Lekuruu** [comment]
Feel free to make a pr, with the client's zip

**Comment by Zordon1337** [comment]
> Feel free to make a pr, with the client's zip

im gonna do this tommorow because i need to patch rest of the ip's, i only patched the one to connect
but anyways here is the current version
[b420.zip](https://github.com/osuTitanic/clients/files/13850559/b420.zip)

**Comment by Lekuruu** [comment]
The client doesn't seem to open for me. Are there any files missing?

**Comment by Zordon1337** [comment]
im gonna check wait

**Comment by Zordon1337** [comment]
nvrmind, i know why. i removed my md5 password from the osu!.cfg thats probably why

**Comment by Lekuruu** [comment]
That shouldn't be the reason why

**Comment by Lekuruu** [comment]
Maybe it needs an older dotnet version. Let me try that...

**Comment by Zordon1337** [comment]
hmm, it works fine for me

**Comment by Zordon1337** [comment]
> Maybe it needs an older dotnet version. Let me try that...

yeah, maybe thats why

**Comment by Zordon1337** [comment]
![image](https://github.com/osuTitanic/clients/assets/65111609/cea68812-4135-4038-922e-29f493ac3ea4)

**Comment by Zordon1337** [comment]
yeah, now i get correct error "version missmatch" instead of wrong password

**Comment by Lekuruu** [comment]
yup, i changed that

**Comment by Lekuruu** [comment]
Seems that the client got compiled from the leaked source code, lol

**Comment by Zordon1337** [comment]
> Seems that the client got compiled from the leaked source code, lol

wait, there was other leak than the one from 2016/17?

**Comment by Lekuruu** [comment]
If you look at the original file date, you can see its not from 2009
